var fs = require('fs');
var router = require('base-apps-router');
const concat = require('concat-files');

module.exports = {

  conventions: {
    assets:   /^(app)(\\|\/)(assets)/,
    ignored:  [/\/_/, /\.(spec|scenario)\.(js$)/, 'test/mockfirebase.js']
  },

  paths: {
    'public':   'public',
    'watched':  ['app']
  },

  files: {
    javascripts: {
      joinTo: {
        'js/app.js':  [/^app/,"!**/*.spec.js"],
        'js/vendor.js':  [/^(?!app)/,/^(?!test)/,"!**/*.spec.js"]
      }
    },
    stylesheets: {
      joinTo: '/css/app.css'
    }
  },

  plugins: {
    babel: {
      presets: ['es2015']
    },
    eslint: {
      // do not run against autogenerated config-routes.js file
      pattern: /^(app)\/(?!config).*\.js?$/
    },
    htmlPages: {
      forceRemoveFrontMatter: true
    },
    modernizr: {
      destination: 'js/modernizr.js',
      options: [],
      tests: ['flexbox']
    }
  },

  hooks: {
    preCompile: (done) => {
      router({
        src: 'app/**/*.html',
        path: 'app/config/config-routes.js',
        root: 'app',
        library: 'node',
        overwrite: true
      }).then(() => {
        concat([
          'node_modules/@greenhousegames/smash-dot/node_modules/phaser/build/custom/pixi.min.js',
          'node_modules/@greenhousegames/smash-dot/node_modules/phaser/build/custom/phaser-no-physics.min.js'
        ], 'app/assets/js/phaser.js', () => {
          concat([
            'node_modules/@greenhousegames/smash-dot/node_modules/phaser-kinetic-scrolling-plugin/dist/phaser-kinetic-scrolling-plugin.min.js',
            'node_modules/@greenhousegames/smash-dot/node_modules/phaser-ads/build/phaser-ads.min.js'
          ], 'app/assets/js/phaser-plugins.js', done);
        });
      });
    }
  }
};
