# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "public"
  # Paths to game repos
  games:
    smashdot:
      src:
        - "node_modules/@greenhousegames/smash-dot-cordova/dist/www/**/*"
      dest: "public/smashdot/play"
    rock_paper_scissors:
      src:
        - "node_modules/@greenhousegames/rock-paper-scissors-cordova/dist/www/**/*"
      dest: "public/rock-paper-scissors/play"
